import { ChangeDetectionStrategy, Component, computed, effect, inject, input, signal } from '@angular/core';
import { FormControl, FormGroup, NonNullableFormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { BusinessImpactMetric, Screenshot, Software, SoftwareCategory, Visibility } from '../../core/models/software.model';
import { MediaUploadService } from '../../core/services/media-upload.service';
import { SoftwareService } from '../../core/services/software.service';
import { Icon } from '../../shared/components/icon/icon';
import { PageHeader } from '../../shared/components/page-header/page-header';

interface ProjectForm { name: FormControl<string>; slug: FormControl<string>; description: FormControl<string>; category: FormControl<SoftwareCategory>; techStack: FormControl<string>; tags: FormControl<string>; coverImage: FormControl<string>; screenshots: FormControl<string>; demoUrl: FormControl<string>; liveUrl: FormControl<string>; repoUrl: FormControl<string>; outcome: FormControl<string>; metrics: FormControl<string>; challenge: FormControl<string>; solution: FormControl<string>; featured: FormControl<boolean>; visibility: FormControl<Visibility>; }
@Component({selector:'ge-software-form',standalone:true,changeDetection:ChangeDetectionStrategy.OnPush,imports:[ReactiveFormsModule,RouterLink,PageHeader,Icon],templateUrl:'./software-form.html'})
export class SoftwareForm {
  readonly id=input<string>(); private readonly fb=inject(NonNullableFormBuilder); private readonly projects=inject(SoftwareService); private readonly router=inject(Router); private readonly media=inject(MediaUploadService);
  protected readonly editing=computed(()=>!!this.id()); protected readonly uploadsEnabled=this.media.enabled; protected readonly uploading=signal(false); protected readonly uploadError=signal<string|null>(null); protected readonly saved=signal(false); protected readonly step=signal<1|2|3>(1);
  protected readonly categories:readonly SoftwareCategory[]=['Website','Software','Dashboard','Automation','Integration']; protected readonly visibilities:readonly {value:Visibility;label:string}[]=[{value:'public',label:'Public'},{value:'client-only',label:'Client-only'},{value:'private',label:'Private'}];
  protected readonly form:FormGroup<ProjectForm>=this.fb.group<ProjectForm>({name:this.fb.control('',{validators:[Validators.required,Validators.minLength(2)]}),slug:this.fb.control('',{validators:[Validators.required,Validators.pattern(/^[a-z0-9-]+$/)]}),description:this.fb.control('',{validators:[Validators.required,Validators.maxLength(280)]}),category:this.fb.control<SoftwareCategory>('Website'),techStack:this.fb.control(''),tags:this.fb.control(''),coverImage:this.fb.control(''),screenshots:this.fb.control(''),demoUrl:this.fb.control(''),liveUrl:this.fb.control(''),repoUrl:this.fb.control(''),outcome:this.fb.control(''),metrics:this.fb.control(''),challenge:this.fb.control(''),solution:this.fb.control(''),featured:this.fb.control(false),visibility:this.fb.control<Visibility>('public')});
  constructor(){effect(()=>{const s=this.id()?this.projects.getById(this.id()!):undefined;if(s)this.patchFrom(s);});this.form.controls.name.valueChanges.subscribe(name=>{if(!this.form.controls.slug.dirty&&!this.editing())this.form.controls.slug.setValue(this.slugify(name),{emitEvent:false});});}
  protected invalid(name:keyof ProjectForm):boolean{const c=this.form.controls[name];return c.invalid&&(c.dirty||c.touched);} protected go(step:1|2|3):void{this.step.set(step);} protected selectStep(step:number):void{if(step===1||step===2||step===3)this.step.set(step);}
  protected save(published:boolean):void{if(this.form.invalid){this.form.markAllAsTouched();this.step.set(1);return;}const p=this.toProject(published);if(this.editing())this.projects.update(p.id,p);else this.projects.create(p);this.saved.set(true);setTimeout(()=>this.router.navigate(['/admin/projects']),500);}
  protected async uploadCover(e:Event):Promise<void>{const f=(e.target as HTMLInputElement).files?.[0];if(f)await this.upload(f,'thumbnails',url=>this.form.controls.coverImage.setValue(url));}
  protected async uploadGallery(e:Event):Promise<void>{const files=Array.from((e.target as HTMLInputElement).files??[]);if(!files.length||!this.uploadsEnabled)return;this.uploading.set(true);try{const urls=await this.media.uploadMany(files,'screenshots');this.form.controls.screenshots.setValue([this.form.controls.screenshots.value,...urls].filter(Boolean).join('\n'));}catch{this.uploadError.set('Image upload failed. Paste image URLs instead.');}finally{this.uploading.set(false);}}
  private async upload(f:File,folder:string,set:(url:string)=>void):Promise<void>{if(!this.uploadsEnabled)return;this.uploading.set(true);try{set(await this.media.uploadImage(f,folder));}catch{this.uploadError.set('Image upload failed. Paste an image URL instead.');}finally{this.uploading.set(false);}}
  private patchFrom(s:Software):void{this.form.patchValue({name:s.name,slug:s.slug,description:s.description,category:s.category,techStack:s.techStack.map(t=>t.name).join(', '),tags:s.tags.join(', '),coverImage:s.coverImage,screenshots:s.screenshots.map(x=>x.url).join('\n'),demoUrl:s.demoVideoUrl??s.videos[0]?.url??'',liveUrl:s.liveUrl??'',repoUrl:s.repoUrl??'',outcome:s.outcome??s.solution,metrics:(s.metrics??s.impact).slice(0,3).map(m=>`${m.label}: ${m.value}`).join('\n'),challenge:s.caseStudy?.problem??s.problem,solution:s.caseStudy?.solution??s.solution,featured:s.featured,visibility:s.visibility});}
  private toProject(published:boolean):Software{const v=this.form.getRawValue(),old=this.id()?this.projects.getById(this.id()!):undefined,now=new Date().toISOString().slice(0,10),metrics=this.toMetrics(v.metrics),outcome=v.outcome.trim();return {id:old?.id??`sw-${Math.random().toString(36).slice(2,8)}`,slug:v.slug,name:v.name.trim(),tagline:v.description.trim(),description:v.description.trim(),longDescription:old?.longDescription??v.description.trim(),problem:v.challenge.trim()||old?.problem||'',manualPainPoints:old?.manualPainPoints??[],solution:v.solution.trim()||outcome||old?.solution||v.description.trim(),category:v.category,demoCategory:old?.demoCategory??'Operations',status:published?'Live':'In Development',visibility:v.visibility,featured:v.featured,coverImage:v.coverImage,accentColor:old?.accentColor??'#6d49ff',accentColor2:old?.accentColor2??'#f43bb8',techStack:this.list(v.techStack).map(name=>({name})),screenshots:this.lines(v.screenshots).map((url,i):Screenshot=>({id:old?.screenshots[i]?.id??`ss-${i}-${Date.now()}`,url,thumbnail:url,caption:`${v.name} screenshot ${i+1}`})),videos:v.demoUrl?[{id:old?.videos[0]?.id??`vid-${Date.now()}`,title:`${v.name} demo`,url:v.demoUrl,thumbnail:v.coverImage,durationSeconds:60}]:old?.videos??[],impact:metrics.length?metrics:old?.impact??[],keyFeatures:old?.keyFeatures??[],headlineMetric:metrics[0]??old?.headlineMetric??{label:'Outcome',value:'—'},timeSaved:old?.timeSaved??'',liveUrl:v.liveUrl||undefined,repoUrl:v.repoUrl||undefined,demoVideoUrl:v.demoUrl||undefined,pricing:old?.pricing??'Custom Quote',rating:old?.rating??0,clients:old?.clients??0,impactScore:old?.impactScore??0,launchedAt:old?.launchedAt??now,updatedAt:now,tags:this.list(v.tags),published,outcome:outcome||undefined,metrics:metrics.length?metrics:undefined,caseStudy:(v.challenge||v.solution||outcome)?{executiveSummary:outcome,problem:v.challenge,solution:v.solution,implementation:'',technologyUsed:this.list(v.techStack),timeline:'',challenges:'',results:outcome,gallery:[],downloads:[]}:old?.caseStudy};}
  private list(v:string):string[]{return v.split(',').map(x=>x.trim()).filter(Boolean);} private lines(v:string):string[]{return v.split('\n').map(x=>x.trim()).filter(Boolean);} private toMetrics(v:string):BusinessImpactMetric[]{return this.lines(v).slice(0,3).map((line,i)=>{const [label,...parts]=line.split(':');return {label:label.trim()||`Result ${i+1}`,value:parts.join(':').trim()||'—',trend:'up' as const};});} private slugify(v:string):string{return v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');}
}
